"""
Generate comprehensive hardcoded-color overrides for the DARK themes.

The dark themes already neutralize a FEW hardcoded Tailwind pastels (red/green/
blue/orange/yellow at 50/100 bg + 800 text) so they don't clash on dark
backgrounds. But category/decorative colors use many more families (purple,
indigo, amber, teal, rose, etc.) and more shades — those fell through the gap
and rendered as light-pastel-on-dark. This generates the full coverage block.

Output is appended to styles/chaos-themes.css inside a marked region.
"""

DARK_THEMES = ['theme-ace', 'theme-caelan', 'theme-calm', 'theme-cyberpunk', 'theme-deep-current', 'theme-grok']
FAMILIES = ['red','orange','amber','yellow','lime','green','emerald','teal','cyan','sky','blue','indigo','violet','purple','fuchsia','pink','rose']

BG_SHADES = ['50','100','200','300']
TEXT_SHADES = ['600','700','800','900']
BORDER_SHADES = ['100','200','300']

def selectors(prefix, shades):
    sels = []
    for theme in DARK_THEMES:
        for fam in FAMILIES:
            for sh in shades:
                sels.append(f'body.{theme} .{prefix}-{fam}-{sh}')
    return ',\n'.join(sels)

out = []
out.append('\n/* ============================================================================')
out.append(' * COMPREHENSIVE HARDCODED-COLOR NEUTRALIZATION FOR DARK THEMES (CHA-271)')
out.append(' * Generated by scripts/gen_theme_color_overrides.py — do not hand-edit; regen.')
out.append(' * Extends the partial red/green/blue/orange/yellow coverage above to ALL')
out.append(' * Tailwind color families + shades, so category/decorative pastels adapt')
out.append(' * to dark themes instead of rendering as light-pastel-on-dark.')
out.append(' * ========================================================================== */\n')

out.append('/* Pale fixed backgrounds -> subtle translucent tint that reads on any dark bg */')
out.append(selectors('bg', BG_SHADES) + ' {')
out.append('  background-color: rgba(255, 255, 255, 0.08) !important;')
out.append('}\n')

out.append('/* Dark colored text -> theme text color, brightened, so it stays legible */')
out.append(selectors('text', TEXT_SHADES) + ' {')
out.append('  color: inherit !important;')
out.append('  filter: brightness(1.8) !important;')
out.append('}\n')

out.append('/* Pale colored borders -> soft theme border */')
out.append(selectors('border', BORDER_SHADES) + ' {')
out.append('  border-color: var(--border-soft, rgba(255,255,255,0.2)) !important;')
out.append('}\n')

block = '\n'.join(out)

path = 'styles/chaos-themes.css'
with open(path, encoding='utf-8') as f:
    css = f.read()

MARKER = '/* COMPREHENSIVE HARDCODED-COLOR NEUTRALIZATION FOR DARK THEMES (CHA-271)'
if MARKER in css:
    # strip prior generated region (from the banner comment to EOF if it's last)
    idx = css.index('\n/* ====================================================================' +
                    '========\n * COMPREHENSIVE')
    css = css[:idx].rstrip() + '\n'
    print('Replaced existing generated block.')

with open(path, 'w', encoding='utf-8') as f:
    f.write(css.rstrip() + '\n' + block + '\n')

print(f'Appended {len(DARK_THEMES)} themes x {len(FAMILIES)} families coverage.')
print(f'bg shades: {BG_SHADES}, text shades: {TEXT_SHADES}, border shades: {BORDER_SHADES}')
