"""
Generate per-family TONED-DOWN hardcoded-color overrides for the DARK themes.

Hardcoded Tailwind pastels (bg-purple-100 text-purple-800 etc.) clash on dark
themes. Earlier approach flattened them all to uniform translucent white, which
killed color identity. This version keeps each family's HUE but tones it way
down: a low-opacity tint background + a light, readable same-hue text. So a
category card stays recognizably "purple" or "blue" but muted to fit a dark
theme — "some color, not bright."

Theme-scoped (only the dark themes), so light themes keep their native pastels.
Appended to styles/chaos-themes.css inside a marked region. Regenerate; don't
hand-edit.
"""

DARK_THEMES = ['theme-ace', 'theme-caelan', 'theme-calm', 'theme-cyberpunk',
               'theme-deep-current', 'theme-grok', 'theme-wicked', 'theme-accessibility']

FAMILIES = ['red','orange','amber','yellow','lime','green','emerald','teal','cyan',
            'sky','blue','indigo','violet','purple','fuchsia','pink','rose']

# (family) -> (rgb of -500 for bg/border tint, rgb of -300 for readable text on dark)
RGB500 = {
    'red':'239 68 68','orange':'249 115 22','amber':'245 158 11','yellow':'234 179 8',
    'lime':'132 204 22','green':'34 197 94','emerald':'16 185 129','teal':'20 184 166',
    'cyan':'6 182 212','sky':'14 165 233','blue':'59 130 246','indigo':'99 102 241',
    'violet':'139 92 246','purple':'168 85 247','fuchsia':'217 70 239','pink':'236 72 153',
    'rose':'244 63 94',
}
RGB300 = {
    'red':'252 165 165','orange':'253 186 116','amber':'252 211 77','yellow':'253 224 71',
    'lime':'190 242 100','green':'134 239 172','emerald':'110 231 183','teal':'94 234 212',
    'cyan':'103 232 249','sky':'125 211 252','blue':'147 197 253','indigo':'165 180 252',
    'violet':'196 181 253','purple':'216 180 254','fuchsia':'240 171 252','pink':'249 168 212',
    'rose':'253 164 175',
}

BG_SHADES = ['50','100','200','300']
TEXT_SHADES = ['600','700','800','900']
BORDER_SHADES = ['100','200','300']

def rgb(s):  # "239 68 68" -> "239, 68, 68"
    return s.replace(' ', ', ')

lines = []
lines.append('\n/* ============================================================================')
lines.append(' * TONED-DOWN HARDCODED-COLOR OVERRIDES FOR DARK THEMES (CHA-271)')
lines.append(' * Generated by scripts/gen_theme_color_overrides.py — do not hand-edit; regen.')
lines.append(' * Each Tailwind color family keeps its HUE but muted for dark themes:')
lines.append(' *   bg pastels  -> rgba(hue, 0.15) tint   (some color, not bright)')
lines.append(' *   dark text   -> light same-hue (-300)  (readable, still colored)')
lines.append(' *   pale border -> rgba(hue, 0.30)')
lines.append(' * Theme-scoped to the dark themes; light themes keep native pastels.')
lines.append(' * ========================================================================== */\n')

for fam in FAMILIES:
    # backgrounds
    sels = ',\n'.join(f'body.{t} .bg-{fam}-{sh}' for t in DARK_THEMES for sh in BG_SHADES)
    lines.append(sels + ' {')
    lines.append(f'  background-color: rgba({rgb(RGB500[fam])}, 0.15) !important;')
    lines.append('}')
    # text
    sels = ',\n'.join(f'body.{t} .text-{fam}-{sh}' for t in DARK_THEMES for sh in TEXT_SHADES)
    lines.append(sels + ' {')
    lines.append(f'  color: rgb({rgb(RGB300[fam])}) !important;')
    lines.append('  filter: none !important;')
    lines.append('}')
    # borders
    sels = ',\n'.join(f'body.{t} .border-{fam}-{sh}' for t in DARK_THEMES for sh in BORDER_SHADES)
    lines.append(sels + ' {')
    lines.append(f'  border-color: rgba({rgb(RGB500[fam])}, 0.30) !important;')
    lines.append('}\n')

block = '\n'.join(lines)

path = 'styles/chaos-themes.css'
with open(path, encoding='utf-8') as f:
    css = f.read()

# strip any prior generated region (either old banner text)
for marker in ('TONED-DOWN HARDCODED-COLOR OVERRIDES FOR DARK THEMES',
               'COMPREHENSIVE HARDCODED-COLOR NEUTRALIZATION FOR DARK THEMES'):
    i = css.find(marker)
    if i != -1:
        start = css.rfind('/* ===', 0, i)
        css = css[:start].rstrip() + '\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(css.rstrip() + '\n' + block + '\n')

print(f'Wrote toned-down overrides: {len(DARK_THEMES)} themes x {len(FAMILIES)} families.')
