/*
 * Copyright (c) 2025-2026 Chaos Cascade
 * Created by: Ren & Ace
 *
 * Persistent local-network HTTP server for the auto-sync feature. Started
 * once during app setup and runs for the lifetime of the process.
 *
 * Routes:
 *   GET  /healthz       — liveness probe (no auth)
 *   POST /pair          — first-time pairing (one-time pairing_token, only
 *                          accepted while a pairing window is open)
 *   POST /sync          — auth'd peer sync (HMAC-SHA256 over body)
 *
 * Auth header on /sync:
 *   X-Chaos-Auth: <peer_id>:<base64(hmac_sha256(shared_secret, body))>
 *
 * The server consults the persistent peer registry (peers.rs) to validate
 * incoming peers and to record liveness signals (last_known_ip, etc.).
 *
 * Data flow for /sync responses: the responder doesn't have direct access
 * to the database (Dexie lives in the webview). The frontend pushes a
 * fresh snapshot via `sync_publish_snapshot` whenever data changes; the
 * server returns the cached snapshot. A snapshot older than five minutes
 * is still served, but is flagged in the response so the caller can
 * choose whether to import it.
 */

use crate::peers::{self, Peer, PeerStore};
use serde::{Deserialize, Serialize};
use std::io::{Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::sync::{Arc, Mutex};
use std::time::Duration;

const MAX_BODY_BYTES: usize = 32 * 1024 * 1024; // 32 MiB cap on request body
const READ_TIMEOUT: Duration = Duration::from_secs(60);
const WRITE_TIMEOUT: Duration = Duration::from_secs(60);
const PAIRING_WINDOW_SECS: u64 = 120;

// =============================================================================
// SERVER STATE
// =============================================================================

#[derive(Debug, Clone)]
pub struct CachedSnapshot {
    /// Database export as JSON (whatever the frontend's exportAllData()
    /// produces). The server is opaque to its structure.
    pub data_json: String,
    /// PIN hash this snapshot represents. Used for the cross-PIN mismatch
    /// check on /sync.
    pub pin_hash: String,
    /// Friendly device name from the frontend (typically `os.hostname()`
    /// or a user-overridden label).
    pub device_name: String,
    /// Unix seconds when the snapshot was published.
    pub updated_unix: u64,
}

#[derive(Debug, Clone)]
pub struct PairingWindow {
    pub token: String,
    /// PIN hash under which a successful pair will be recorded. The
    /// frontend captures this when it opens the window so a PIN switch
    /// after-the-fact doesn't accidentally cross-attribute the new peer.
    pub pin_hash: String,
    pub expires_unix: u64,
}

pub struct ServerState {
    pub peer_store: Arc<PeerStore>,
    pub cached_snapshot: Mutex<Option<CachedSnapshot>>,
    pub pairing_window: Mutex<Option<PairingWindow>>,
    /// Bound port — set after the listener actually binds, exposed to
    /// the frontend so it can build QR payloads.
    pub bound_port: Mutex<Option<u16>>,
}

impl ServerState {
    pub fn new(peer_store: Arc<PeerStore>) -> Self {
        Self {
            peer_store,
            cached_snapshot: Mutex::new(None),
            pairing_window: Mutex::new(None),
            bound_port: Mutex::new(None),
        }
    }
}

// =============================================================================
// WIRE TYPES
// =============================================================================

/// QR payload for the new persistent-server pair flow.
#[derive(Debug, Serialize, Deserialize)]
pub struct PairQr {
    pub ip: String,
    pub port: u16,
    pub host_peer_id: String,
    pub pairing_token: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct PairRequest {
    pub pairing_token: String,
    pub scanner_peer_id: String,
    pub scanner_device_name: String,
    pub scanner_pin_hash: String,
    /// 32-byte secret (base64) generated by the scanner. Both sides store
    /// it; future /sync requests are HMACed with it.
    pub shared_secret: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct PairResponse {
    pub success: bool,
    pub host_peer_id: String,
    pub host_device_name: String,
    pub host_pin_hash: String,
    pub message: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncRequest {
    pub data: String,
    pub pin_hash: String,
    pub timestamp: u64,
    pub sender_device_name: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncResponse {
    pub success: bool,
    /// One of: ok | pin_mismatch | peer_not_found | bad_auth | snapshot_missing
    pub reason: Option<String>,
    pub data: Option<String>,
    pub device_name: Option<String>,
    pub snapshot_age_secs: Option<u64>,
}

// =============================================================================
// PUBLIC API
// =============================================================================

/// Start the persistent server. Returns the bound port so the caller can
/// stash it for QR payload generation. The server runs in a background
/// std::thread (one accept loop) which spawns a fresh thread per connection.
/// We're not under heavy load — at most a handful of connections per minute
/// from the user's own paired devices — so a thread-per-conn model is fine
/// and avoids dragging tokio runtimes through this module.
pub fn spawn_server(state: Arc<ServerState>) -> Result<u16, String> {
    // Try to re-use the previously persisted port so peers don't have to
    // re-pair after every restart.
    let preferred = state.peer_store.self_port().unwrap_or(None);
    let listener = bind_listener(preferred)?;
    let port = listener
        .local_addr()
        .map_err(|e| format!("Failed to read bound port: {}", e))?
        .port();

    state.peer_store.set_self_port(port)?;
    *state.bound_port.lock().map_err(|e| e.to_string())? = Some(port);

    std::thread::Builder::new()
        .name("chaos-sync-accept".into())
        .spawn(move || accept_loop(listener, state))
        .map_err(|e| format!("Failed to spawn server thread: {}", e))?;

    Ok(port)
}

fn bind_listener(preferred: Option<u16>) -> Result<TcpListener, String> {
    if let Some(p) = preferred {
        if let Ok(l) = TcpListener::bind(("0.0.0.0", p)) {
            return Ok(l);
        }
        // Preferred port unavailable — fall through to ephemeral.
    }
    TcpListener::bind("0.0.0.0:0")
        .map_err(|e| format!("Failed to bind sync server: {}", e))
}

fn accept_loop(listener: TcpListener, state: Arc<ServerState>) {
    for incoming in listener.incoming() {
        match incoming {
            Ok(stream) => {
                let state = Arc::clone(&state);
                std::thread::Builder::new()
                    .name("chaos-sync-conn".into())
                    .spawn(move || {
                        if let Err(e) = handle_connection(stream, state) {
                            // Server-side errors don't propagate back to
                            // the user — log and move on.
                            eprintln!("[chaos-sync] connection error: {}", e);
                        }
                    })
                    .ok();
            }
            Err(e) => {
                eprintln!("[chaos-sync] accept error: {}", e);
                // brief backoff on accept errors so we don't spin
                std::thread::sleep(Duration::from_millis(200));
            }
        }
    }
}

// =============================================================================
// CONNECTION HANDLING
// =============================================================================

fn handle_connection(mut stream: TcpStream, state: Arc<ServerState>) -> Result<(), String> {
    stream
        .set_read_timeout(Some(READ_TIMEOUT))
        .map_err(|e| format!("set_read_timeout: {}", e))?;
    stream
        .set_write_timeout(Some(WRITE_TIMEOUT))
        .map_err(|e| format!("set_write_timeout: {}", e))?;

    let peer_addr = stream
        .peer_addr()
        .map_err(|e| format!("peer_addr: {}", e))?;
    let (method, path, headers, body) = read_http_request(&mut stream)?;

    match (method.as_str(), path.as_str()) {
        ("GET", "/healthz") => write_json(&mut stream, 200, &serde_json::json!({"ok": true})),
        ("POST", "/pair") => {
            let resp = handle_pair(&body, &state)?;
            write_json(&mut stream, if resp.success { 200 } else { 400 }, &resp)
        }
        ("POST", "/sync") => {
            let resp = handle_sync(&headers, &body, peer_addr, &state)?;
            // Always 200 — the success flag and reason in the body carry
            // semantics. Returning non-2xx for "wrong PIN" turns into a
            // generic network error on the client and loses the reason.
            write_json(&mut stream, 200, &resp)
        }
        _ => write_json(
            &mut stream,
            404,
            &serde_json::json!({"error": "not found"}),
        ),
    }
}

fn read_http_request(
    stream: &mut TcpStream,
) -> Result<(String, String, Vec<(String, String)>, Vec<u8>), String> {
    let mut buf = Vec::with_capacity(4096);
    let mut tmp = [0u8; 8192];
    let mut header_end: Option<usize> = None;

    while header_end.is_none() {
        let n = stream
            .read(&mut tmp)
            .map_err(|e| format!("read headers: {}", e))?;
        if n == 0 {
            return Err("client closed before sending headers".into());
        }
        buf.extend_from_slice(&tmp[..n]);
        header_end = buf.windows(4).position(|w| w == b"\r\n\r\n").map(|i| i + 4);
        if buf.len() > MAX_BODY_BYTES + 4096 {
            return Err("header section too large".into());
        }
    }
    let header_end = header_end.unwrap();

    let header_text = std::str::from_utf8(&buf[..header_end - 4])
        .map_err(|e| format!("non-utf8 headers: {}", e))?;
    let mut lines = header_text.split("\r\n");
    let request_line = lines.next().ok_or("empty request")?;
    let mut parts = request_line.split_whitespace();
    let method = parts.next().ok_or("missing method")?.to_uppercase();
    let path = parts.next().ok_or("missing path")?.to_string();

    let mut headers: Vec<(String, String)> = Vec::new();
    let mut content_length: usize = 0;
    for line in lines {
        if line.is_empty() {
            continue;
        }
        if let Some(colon) = line.find(':') {
            let name = line[..colon].trim().to_lowercase();
            let value = line[colon + 1..].trim().to_string();
            if name == "content-length" {
                content_length = value.parse().unwrap_or(0);
            }
            headers.push((name, value));
        }
    }

    if content_length > MAX_BODY_BYTES {
        return Err(format!("body too large ({} bytes)", content_length));
    }

    let mut body = buf[header_end..].to_vec();
    while body.len() < content_length {
        let n = stream
            .read(&mut tmp)
            .map_err(|e| format!("read body: {}", e))?;
        if n == 0 {
            return Err("client closed mid-body".into());
        }
        body.extend_from_slice(&tmp[..n]);
    }
    body.truncate(content_length);

    Ok((method, path, headers, body))
}

fn write_json<T: Serialize>(stream: &mut TcpStream, status: u16, body: &T) -> Result<(), String> {
    let payload = serde_json::to_vec(body).map_err(|e| format!("serialize response: {}", e))?;
    let status_text = match status {
        200 => "OK",
        400 => "Bad Request",
        401 => "Unauthorized",
        404 => "Not Found",
        _ => "Error",
    };
    let header = format!(
        "HTTP/1.1 {} {}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
        status,
        status_text,
        payload.len()
    );
    stream
        .write_all(header.as_bytes())
        .map_err(|e| format!("write headers: {}", e))?;
    stream
        .write_all(&payload)
        .map_err(|e| format!("write body: {}", e))?;
    Ok(())
}

// =============================================================================
// /pair
// =============================================================================

fn handle_pair(body: &[u8], state: &ServerState) -> Result<PairResponse, String> {
    let req: PairRequest = match serde_json::from_slice(body) {
        Ok(r) => r,
        Err(e) => {
            return Ok(PairResponse {
                success: false,
                host_peer_id: String::new(),
                host_device_name: String::new(),
                host_pin_hash: String::new(),
                message: Some(format!("Bad pair payload: {}", e)),
            });
        }
    };

    let now = now_unix();

    // Verify pairing window is open and token matches. Take the lock briefly,
    // copy what we need, drop it before any heavy work.
    let (window_pin_hash, window_token) = {
        let mut guard = state.pairing_window.lock().map_err(|e| e.to_string())?;
        match guard.as_ref() {
            Some(w) if w.expires_unix >= now => (w.pin_hash.clone(), w.token.clone()),
            Some(_) => {
                *guard = None;
                return Ok(PairResponse {
                    success: false,
                    host_peer_id: String::new(),
                    host_device_name: String::new(),
                    host_pin_hash: String::new(),
                    message: Some("Pairing window expired. Reopen it on the host device.".into()),
                });
            }
            None => {
                return Ok(PairResponse {
                    success: false,
                    host_peer_id: String::new(),
                    host_device_name: String::new(),
                    host_pin_hash: String::new(),
                    message: Some("No pairing window is open.".into()),
                });
            }
        }
    };

    if !constant_time_eq(window_token.as_bytes(), req.pairing_token.as_bytes()) {
        return Ok(PairResponse {
            success: false,
            host_peer_id: String::new(),
            host_device_name: String::new(),
            host_pin_hash: String::new(),
            message: Some("Pairing token did not match.".into()),
        });
    }

    if !constant_time_eq(window_pin_hash.as_bytes(), req.scanner_pin_hash.as_bytes()) {
        return Ok(PairResponse {
            success: false,
            host_peer_id: String::new(),
            host_device_name: String::new(),
            host_pin_hash: String::new(),
            message: Some("Both devices must be signed in as the same family member to pair.".into()),
        });
    }

    // Persist the new peer.
    let peer = Peer {
        peer_id: req.scanner_peer_id.clone(),
        peer_name: req.scanner_device_name.clone(),
        shared_secret: req.shared_secret.clone(),
        pin_hash: window_pin_hash.clone(),
        last_known_ip: String::new(),
        last_known_port: 0,
        last_seen_unix: now,
        last_synced_unix: 0,
        consecutive_failures: 0,
        first_failure_unix: 0,
    };
    state.peer_store.upsert(peer)?;

    // Pairing window is single-use.
    *state.pairing_window.lock().map_err(|e| e.to_string())? = None;

    let host_peer_id = state.peer_store.self_peer_id()?;
    let host_device_name = hostname_string();

    Ok(PairResponse {
        success: true,
        host_peer_id,
        host_device_name,
        host_pin_hash: window_pin_hash,
        message: None,
    })
}

// =============================================================================
// /sync
// =============================================================================

fn handle_sync(
    headers: &[(String, String)],
    body: &[u8],
    peer_addr: SocketAddr,
    state: &ServerState,
) -> Result<SyncResponse, String> {
    let auth = headers
        .iter()
        .find(|(k, _)| k == "x-chaos-auth")
        .map(|(_, v)| v.clone())
        .unwrap_or_default();

    let (peer_id, mac_b64) = match auth.split_once(':') {
        Some((p, m)) => (p.to_string(), m.to_string()),
        None => {
            return Ok(SyncResponse {
                success: false,
                reason: Some("bad_auth".into()),
                data: None,
                device_name: None,
                snapshot_age_secs: None,
            });
        }
    };

    let peer = match state.peer_store.find(&peer_id)? {
        Some(p) => p,
        None => {
            return Ok(SyncResponse {
                success: false,
                reason: Some("peer_not_found".into()),
                data: None,
                device_name: None,
                snapshot_age_secs: None,
            });
        }
    };

    if !verify_hmac(&peer.shared_secret, body, &mac_b64) {
        return Ok(SyncResponse {
            success: false,
            reason: Some("bad_auth".into()),
            data: None,
            device_name: None,
            snapshot_age_secs: None,
        });
    }

    let req: SyncRequest = match serde_json::from_slice(body) {
        Ok(r) => r,
        Err(e) => {
            return Ok(SyncResponse {
                success: false,
                reason: Some(format!("bad_body:{}", e)),
                data: None,
                device_name: None,
                snapshot_age_secs: None,
            });
        }
    };

    // Snapshot must exist AND match the pin scope of the request. If the
    // host's frontend hasn't pushed a snapshot yet (cold start, hasn't
    // unlocked their PIN, etc.), we report the situation honestly rather
    // than handing back stale data from a different family member.
    let snapshot = state
        .cached_snapshot
        .lock()
        .map_err(|e| e.to_string())?
        .clone();

    let snapshot = match snapshot {
        Some(s) => s,
        None => {
            return Ok(SyncResponse {
                success: false,
                reason: Some("snapshot_missing".into()),
                data: None,
                device_name: None,
                snapshot_age_secs: None,
            });
        }
    };

    if !constant_time_eq(snapshot.pin_hash.as_bytes(), req.pin_hash.as_bytes()) {
        return Ok(SyncResponse {
            success: false,
            reason: Some("pin_mismatch".into()),
            data: None,
            device_name: Some(snapshot.device_name),
            snapshot_age_secs: None,
        });
    }

    // Finally — peer is authenticated, PIN matches. Record liveness.
    let now = now_unix();
    state
        .peer_store
        .record_seen(&peer_id, &peer_addr.ip().to_string(), peer_addr.port(), now)?;
    state.peer_store.record_success(&peer_id, now)?;

    let age = now.saturating_sub(snapshot.updated_unix);

    Ok(SyncResponse {
        success: true,
        reason: Some("ok".into()),
        data: Some(snapshot.data_json),
        device_name: Some(snapshot.device_name),
        snapshot_age_secs: Some(age),
    })
}

// =============================================================================
// HELPERS
// =============================================================================

fn verify_hmac(secret_b64: &str, body: &[u8], mac_b64: &str) -> bool {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    let secret = match STANDARD.decode(secret_b64) {
        Ok(s) => s,
        Err(_) => return false,
    };
    let claimed_mac = match STANDARD.decode(mac_b64) {
        Ok(m) => m,
        Err(_) => return false,
    };

    let mut mac = match <Hmac<Sha256> as Mac>::new_from_slice(&secret) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(body);
    mac.verify_slice(&claimed_mac).is_ok()
}

fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    use subtle::ConstantTimeEq;
    if a.len() != b.len() {
        return false;
    }
    a.ct_eq(b).into()
}

fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn hostname_string() -> String {
    hostname::get()
        .map(|h| h.to_string_lossy().to_string())
        .unwrap_or_else(|_| "Unknown Device".to_string())
}

// =============================================================================
// PAIRING WINDOW + SNAPSHOT (Tauri commands consume these helpers)
// =============================================================================

pub fn open_pairing_window(state: &ServerState, pin_hash: String) -> Result<PairQr, String> {
    let port = state
        .bound_port
        .lock()
        .map_err(|e| e.to_string())?
        .ok_or("Sync server is not running yet")?;
    let token = peers::generate_pairing_token();

    let window = PairingWindow {
        token: token.clone(),
        pin_hash,
        expires_unix: now_unix() + PAIRING_WINDOW_SECS,
    };
    *state.pairing_window.lock().map_err(|e| e.to_string())? = Some(window);

    let host_peer_id = state.peer_store.self_peer_id()?;
    let ip = local_ip()?;

    Ok(PairQr {
        ip,
        port,
        host_peer_id,
        pairing_token: token,
    })
}

pub fn close_pairing_window(state: &ServerState) -> Result<(), String> {
    *state.pairing_window.lock().map_err(|e| e.to_string())? = None;
    Ok(())
}

pub fn publish_snapshot(state: &ServerState, snap: CachedSnapshot) -> Result<(), String> {
    *state.cached_snapshot.lock().map_err(|e| e.to_string())? = Some(snap);
    Ok(())
}

fn local_ip() -> Result<String, String> {
    let socket = std::net::UdpSocket::bind("0.0.0.0:0")
        .map_err(|e| format!("Failed to bind UDP socket: {}", e))?;
    socket
        .connect("8.8.8.8:80")
        .map_err(|e| format!("Failed to determine local IP: {}", e))?;
    let addr = socket
        .local_addr()
        .map_err(|e| format!("Failed to get local address: {}", e))?;
    Ok(addr.ip().to_string())
}
